// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn-wuZeyhTYBRMFwS_NEJyF4_ug5f2osY',
    appId: '1:88105561760:web:42437c50bdaaf68492a3c5',
    messagingSenderId: '88105561760',
    projectId: 'nicholas-cpd-home',
    authDomain: 'nicholas-cpd-home.firebaseapp.com',
    storageBucket: 'nicholas-cpd-home.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeTOcDTRbvEbcFE4Dl8fmCp76xr6fi3EU',
    appId: '1:88105561760:android:090298918f8dede892a3c5',
    messagingSenderId: '88105561760',
    projectId: 'nicholas-cpd-home',
    storageBucket: 'nicholas-cpd-home.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClv_mfEBYRSMYuHY4r31byMpTznHc8m-E',
    appId: '1:88105561760:ios:0c7dcd63b625eed592a3c5',
    messagingSenderId: '88105561760',
    projectId: 'nicholas-cpd-home',
    storageBucket: 'nicholas-cpd-home.firebasestorage.app',
    iosBundleId: 'com.example.nicholasCpdHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClv_mfEBYRSMYuHY4r31byMpTznHc8m-E',
    appId: '1:88105561760:ios:0c7dcd63b625eed592a3c5',
    messagingSenderId: '88105561760',
    projectId: 'nicholas-cpd-home',
    storageBucket: 'nicholas-cpd-home.firebasestorage.app',
    iosBundleId: 'com.example.nicholasCpdHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn-wuZeyhTYBRMFwS_NEJyF4_ug5f2osY',
    appId: '1:88105561760:web:b37c2a63f64d540692a3c5',
    messagingSenderId: '88105561760',
    projectId: 'nicholas-cpd-home',
    authDomain: 'nicholas-cpd-home.firebaseapp.com',
    storageBucket: 'nicholas-cpd-home.firebasestorage.app',
  );
}
